Repository devhubapp/devhub, pull requests merged in 2019-01, with the labels that each got.

#89 Design Tweaks
  packages/components/src/components/cards/partials/CardItemId.tsx
  packages/components/src/components/cards/partials/rows/IssueOrPullRequestRow.tsx
  packages/components/src/components/columns/ColumnHeaderItem.tsx
  packages/components/src/components/columns/ModalColumn.tsx
  packages/components/src/components/common/CenterGuide.tsx
  packages/components/src/components/common/Checkbox.tsx
  packages/components/src/components/common/FAB.tsx
  packages/components/src/components/common/Label.tsx
  packages/components/src/components/common/Separator.tsx
  packages/components/src/components/context/ColumnWidthContext.tsx
  packages/components/src/components/layout/FABRenderer.tsx
  packages/components/src/components/layout/Sidebar.tsx
  packages/components/src/components/modals/AddColumnModal.tsx
  packages/components/src/components/modals/SettingsModal.tsx
  packages/components/src/components/widgets/ThemePreference.tsx
  packages/components/src/styles/styles.ts
Labels: UX, design

#94 Add some animations and transitions
  packages/components/package.json
  packages/components/src/components/columns/ColumnOptionsRow.tsx
  packages/components/src/components/columns/EventOrNotificationColumn.tsx
  packages/components/src/components/columns/ModalColumn.tsx
  packages/components/src/components/common/AccordionView.tsx
  packages/components/src/components/common/Separator.tsx
  packages/components/src/components/common/TextInput.tsx
  packages/components/src/components/layout/Sidebar.tsx
  packages/components/src/components/modals/AddColumnDetailsModal.tsx
  packages/components/src/components/modals/AddColumnModal.tsx
  packages/components/src/components/modals/EnterpriseSetupModal.tsx
  packages/components/src/components/modals/ModalRenderer.tsx
  packages/components/src/components/modals/SettingsModal.tsx
  packages/components/src/redux/reducers/navigation.ts
  packages/components/src/screens/MainScreen.tsx
  packages/core/src/types/devhub.ts
  yarn.lock
Labels: UX, enhancement

#93 Make contributions easier
  .gitpod.yml
  README.md
Labels: integrations, suggestion
